(* ::Package:: *)

(* ::Input:: *)
(*SetDirectory[NotebookDirectory[]];*)


(* ::Title:: *)
(*2023 Day 17*)


(* ::Input:: *)
(*Catch[Module[{dists=ConstantArray[{},10],memo=<||>,pt,dir,input},*)
(*input=ArrayPad[ToExpression@Characters@ReadList["17.txt",String],1];*)
(*dists[[1]]={{2+2I,I}};*)
(*Do[*)
(*Module[{j=Mod[i,10,1]},*)
(*While[dists[[j]]!={},*)
(*{pt,dir}=First[dists[[j]]];*)
(*dists[[j]]=Rest[dists[[j]]];*)
(*If[ReIm[pt]==Dimensions[input]-1,Throw[i-1]];*)
(*If[KeyFreeQ[memo,{pt,dir}],*)
(*memo[[Key[{pt,dir}]]]=dir;*)
(*With[{d=Normalize[dir]},*)
(*If[Norm[dir]<3&&input[[Sequence@@ReIm[pt+d]]]!=0,*)
(*AppendTo[dists[[Mod[i+input[[Sequence@@ReIm[pt+d]]],10,1]]],{pt+d,dir+d}]];*)
(*If[input[[Sequence@@ReIm[pt+d*-I]]]!=0,*)
(*AppendTo[dists[[Mod[i+input[[Sequence@@ReIm[pt+d*-I]]],10,1]]],{pt+d*-I,d*-I}]];*)
(*If[input[[Sequence@@ReIm[pt+d*I]]]!=0,*)
(*AppendTo[dists[[Mod[i+input[[Sequence@@ReIm[pt+d*I]]],10,1]]],{pt+d*I,d*I}]]]]]]*)
(*,{i,\[Infinity]}]]]*)


(* ::Input:: *)
(*Catch[Module[{dists=ConstantArray[{},10],memo=<||>,pt,dir,input},*)
(*input=ArrayPad[ToExpression@Characters@ReadList["17.txt",String],1];*)
(*dists[[1]]={{2+2I,I,0},{2+2I,1,0}};*)
(*Do[*)
(*Module[{j=Mod[i,10,1],n},*)
(*While[dists[[j]]!={},*)
(*{pt,dir,n}=First[dists[[j]]];*)
(*dists[[j]]=Rest[dists[[j]]];*)
(*With[{d=dir},*)
(*If[ReIm[pt]==Dimensions[input]-1&&n>=4,Throw[i-1]];*)
(*If[KeyFreeQ[memo,{pt,dir,n}],*)
(*memo[[Key[{pt,dir,n}]]]=n;*)
(*If[n<10&&input[[Sequence@@ReIm[pt+d]]]!=0,*)
(*AppendTo[dists[[Mod[i+input[[Sequence@@ReIm[pt+d]]],10,1]]],{pt+d,d,n+1}]];*)
(*If[n>=4,*)
(*If[input[[Sequence@@ReIm[pt+d*-I]]]!=0,*)
(*AppendTo[dists[[Mod[i+input[[Sequence@@ReIm[pt+d*-I]]],10,1]]],{pt+d*-I,d*-I,1}]];*)
(*If[input[[Sequence@@ReIm[pt+d*I]]]!=0,*)
(*AppendTo[dists[[Mod[i+input[[Sequence@@ReIm[pt+d*I]]],10,1]]],{pt+d*I,d*I,1}]]]]]]]*)
(*,{i,\[Infinity]}]]]*)
